### ISSUE TITLE
Compiling a package

### ISSUE THREAD

**Issue by oleua** [trinidude4/sane-airscan#1]
Would you be so kind to describe, how I may compile the sane-airscan package for my router Nexx WT3020 with installed OpenWrt 21.02? Please, explain in steps, how to add the backend. Thanks!

**Comment by trinidude4** [comment]
I'm not an expert with this and I don't have my linux machine up right now to test the steps.  You can try following the directions from OpenWRT for building a package:  https://openwrt.org/docs/guide-developer/toolchain/single.package
First, you would have to add a custom feed to your OpenWRT build system including the sane-airscan files.  You would also have to select sane-airscan as a Module in menuconfig.

If you don't have an OpenWRT build system set up, you could clone my sane-airscan repo.  You would have to edit the '.config' file to match your router configuration for the Nexx WT3020.  It might be easiest to set up an OpenWRT build system just so you can run menuconfig to generate the '.config' file.  I won't have my linux machine up to go through the steps to generate a config file for your router for at least a week so I can't help you there right now.

Then you could build the package in Github using the workflow I have in my repo.

**Comment by trinidude4** [comment]
I had a chance to generate a .config file that might work to build the sane-airscan package for the Nexx WT3020 (assuming it's not the WT3020A).  The config in the zip can replace the one I use in my repository and the package can be built with the existing workflow.
[config-nexx_wt3020-8m.zip](https://github.com/trinidude4/sane-airscan/files/8847532/config-nexx_wt3020-8m.zip)
